### ISSUE TITLE
How to use in NSTableView

### ISSUE THREAD

**Issue by ioquatix** [taktik/TKTokenField#1]
Is it possible to use TKTokenFieldCell in a NSTableView?

**Comment by aduchate** [comment]
in a view based NSTableView, I imagine you could use the whole the whole token field. If you want to use the cell in a cell based table view, there will be work to do to connect the cell and the table view together

**Comment by aduchate** [comment]
Just added a NSTableView with embedded TKTokenField to the example target

**Comment by ioquatix** [comment]
Awesome. Unfortunately view based tables are a pain for my existing (legacy?) UIs. I'm working on moving more of the code to TKTokenFieldCell so it could work in the table view.
